### ISSUE TITLE
Error after creating collection on server

### ISSUE THREAD

**Issue by pyfection** [pyfection/servare#160]
2019-02-19 10:05:59,548: Internal Server Error: /collection/new_collection/
Traceback (most recent call last):
  File "/home/Pyfection/.virtualenvs/bvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/Pyfection/.virtualenvs/bvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/Pyfection/.virtualenvs/bvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/Pyfection/boarbar/collection/views.py", line 114, in new_collection
    type = CollectionType.objects.get(name=type)
  File "/home/Pyfection/.virtualenvs/bvenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/Pyfection/.virtualenvs/bvenv/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
collection.models.DoesNotExist: CollectionType matching query does not exist.

**Comment by pyfection** [comment]
The reason was that there was no CollectionType
